apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: practica5
  name: front3
   
spec:
 template:
  metadata:
   name: practica5_Luna
   labels:
    type: front3 
  spec:
   containers:
   - image: xstabel/dotnet-core-publish
     name: practica3container
     env:
     - name: GREATINGS
       value: "hola"
     - name: COLOR
       value: "blue"
     ports:
     - containerPort: 8080
     resources: 
      requests:
        memory: 0.2Gi
        cpu: 100m
      limits:
        memory: 0.2Gi
        cpu: 100m
   dnsPolicy: ClusterFirst
   restartPolicy: Always
 replicas: 2
 selector:
  matchLabels:
      type: front3