version: "3.9"
services:
  nginx:
    image: nginx:1.21.4
    container_name: test_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./repo:/var/www
      - ./nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl/
    working_dir: /var/www
    depends_on:
      - php
  php:
    build: ./php/
    image: test_php:test
    container_name: test_php
    volumes:
      - ./repo:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.36
    container_name: test_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password
