version: '3.1'

services:

  adminer:
    image: adminer
    restart: none
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.6
    restart: none
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: jorgedb
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbtest
    volumes:
      - mysqlvol:/var/mysql
volumes:
  mysqlvol: