version: "3.8"
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: exampledb 
    volumes:
      - wordpress:/var/www/html
    secrets:
      - db_password
secrets:
  db_password:
    file: ./db_password.txt
  db_root_password: 
    file: ./db_root_password.txt 
volumes:
  mysql-data: 
  wordpress: 
