AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.8
    Handler: lambda_function.lambda_handler
    Environment:
      Variables:
        TABLE_NAME: !Ref AnunciosTable

Resources:
  AnunciosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler-lamdda-anuncio
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AnunciosTable

  AnunciosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Anuncios
      AttributeDefinitions:
        - AttributeName: titulo
          AttributeType: S
      KeySchema:
        - AttributeName: titulo
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

# Sección para configurar el sitio web estático localmente
LocalStaticWeb:
  Type: AWS::Serverless::Api
  Properties:
    StageName: local
    DefinitionBody:
      swagger: "2.0"
      info:
        title: "Local Static Website"
      paths:
        /:
          get:
            produces:
              - "text/html"
            responses:
              '200':
                description: "HTML content"
                headers:
                  Content-Type:
                    type: "string"
                schema:
                  type: "string"
                example: "<html><body>Hello, world!</body></html>"

Outputs:
  WebsiteURL:
    Value: !Sub "http://localhost:3000/"
