AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AnunciosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./path/to/your/lambda/code
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AnunciosTable
      Environment:
        Variables:
          TABLE_NAME: !Ref AnunciosTable

  AnunciosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Anuncios
      AttributeDefinitions:
        - AttributeName: titulo
          AttributeType: S
      KeySchema:
        - AttributeName: titulo
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  StaticWebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-static-website-bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  StaticWebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: StaticWebBucketOrigin
            DomainName: !GetAtt StaticWebBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: StaticWebBucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  WebsiteURL:
    Value: !GetAtt StaticWebDistribution.DomainName
