FROM alpine:3.17.1
WORKDIR /opt
RUN echo "Welcome to Docker Labs" > opt.txt
WORKDIR /opt/folder1
RUN echo "Welcome to Docker Labs" > folder1.txt
WORKDIR /opt/folder1/folder2
RUN echo "Welcome to Docker Labs" > folder2.txt