apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-practicadatahack
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
      containers:
        - name: mongodb
          image: jorgedb/mongo:4.0.7
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: "/data/db"
        - name: web
          image: jorgedb/web_practicadatahack:1
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 7007
              name: https
          env:
            - name: Version
              value: "1.0"
            - name: Entorno
              value: "Pruebas"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-coches
spec:
  selector:
    app: web
  ports:
    - name: "https"
      protocol: TCP
      port: 7007
      targetPort: 7007
  type: NodePort
