# Usa una imagen base de Nginx
FROM nginx:latest

# Copia un archivo HTML de ejemplo a la carpeta de contenido de Nginx
COPY index.html /usr/share/nginx/html/

# Expon el puerto 80 para el tráfico HTTP
EXPOSE 80
