apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: practica8
  name: front-8
spec:
 template:
  metadata:
   name: practica8_pod_Luna
   labels:
    type: front8 
  spec:
   containers:
   - image: xstabel/dotnet-core-publish
     name: practica6-container
     env:
        - name: DB_USER
          valueFrom:
           secretKeyRef:
            name: secret-backend-user
            key: backend-username
        - name: DB_PASWORD
          valueFrom:
           secretKeyRef:
            name: secret-password-user
            key: db-password
     ports:
     - containerPort: 8080
     resources: 
      requests:
        memory: 0.2Gi
        cpu: 100m
      limits:
        memory: 0.2Gi
        cpu: 100m
   dnsPolicy: ClusterFirst
   restartPolicy: Always
 replicas: 2
 selector:
  matchLabels:
      type: front8