version: '3.1'
services:    
  mongo:
    image: 'mongo:5.0.9'
    restart: always
#    network_mode: "host"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nosql
      MONGO_INITDB_ROOT_PASSWORD: nosql
  mongo-express:
    image: 'mongo-express:0.54.0'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nosql
      ME_CONFIG_MONGODB_ADMINPASSWORD: nosql
      ME_CONFIG_MONGODB_URL: mongodb://nosql:nosql@mongo:27017/
  neo4j:
    image: 'neo4j:4.3.9'
    restart: always
#    network_mode: "host"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/1234    
  jupyter:
    image: 'rafaelgarrote/scipy-notebook:v0.5' 
    restart: always
#    network_mode: "host"
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_LAB_ENABLE=yes
      - GRANT_SUDO=yes
    user: root  
    volumes: 
      - "./work:/home/jovyan/work"
      - "./work/config/cypher_config.yml:/home/jovyan/.jupyter/cypher_config.yml"
    entrypoint: bash -c "start-notebook.sh --NotebookApp.token=''"  
