apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: practica4
  name: front
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front
  template:
    metadata:
      labels:
        type: front
    spec:
      containers:
      - image: xstabel/dotnet-core-publish
        name: practica4
        ports:
        - containerPort: 8080
        resources: {}
