service: datahack-cloud

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:PutBucketPolicy'
            - 's3:PutObjectAcl'
          Resource: '*'
        - Effect: Allow
          Action: '*'
          Resource: '*'

functions:
  insertMessage:
    handler: handler.insert_message
    events:
      - http:
          path: insert-message
          method: post
          cors: true

  getMessages:
    handler: handler.get_messages
    events:
      - http:
          path: get-messages
          method: get
          cors: true

resources:
  Resources:
    MyApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: my-api-gateway
        Description: MSG API Gateway

    StaticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: datahack-msg-bucket
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
        WebsiteConfiguration:
          IndexDocument: index.html
        VersioningConfiguration:
          Status: Enabled

    WebsiteDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt StaticSiteBucket.DomainName
              Id: myStaticSite
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: myStaticSite
            ForwardedValues:
              QueryString: 'false'
            ViewerProtocolPolicy: redirect-to-https

    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: datahack-msg-deploy
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
