apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: practica2
  name: practica2
spec:
  containers:
  - image: xstabel/dotnet-core-publish
    name: practica2
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
