version: "3.8"
services:
  proxy:
    image: nginx:1.13.6
    configs:
      - source: proxy
        target: /etc/nginx/nginx.conf 
    ports:
      - 8080:8000
    networks:
      - front
  api:
    image: edelpa/api
    networks:
      - front
    ports:
      - 80:80
configs:
  proxy:
    # file: ./nginx.conf
    external: true
networks:
  front:
